import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Pre-Publication Review | Henry R. Kaufman, P.C.',
};

export default function Page() {
  return (
    <div id="main">
      <div id="primary">
        <div id="content" role="main">
          <article className="page hentry">
            <header className="entry-header">
              <h1 className="entry-title">Pre-Publication Review</h1>
            </header>
            <div
              className="entry-content"
              dangerouslySetInnerHTML={{
                __html: `<p>&nbsp;</p>
<ul>
<li>Over the past two years, the firm has continued its active book vetting for major publishers. Some of the more important books included, among many others, memoirs of leading presidential candidates (one Republican and one Democratic) in the 2016 election cycle; an autobiography by one of President Trump’s three national security advisers; the memoir of a foreign head of state; the definitive new biography of a recent U.S. President; the memoir of a leading European politician caught up in his country’s financial crisis; a book on the role of local governments in addressing climate change by a former big city mayor; another title in a multi-volume, best-selling historical series and a book of essays by 27 psychiatrists and mental health professionals assessing Donald Trump.</li>
<li>In October 2015, Mr. Kaufman and Mr. Cantwell published the third and final installment of their multipart article, <a href="/wp-content/uploads/2015/11/Top-tips-for-prepublication-review-Part-III-FINAL.pdf" onclick="__gaTracker('send', 'event', 'download', '/wp-content/uploads/2015/11/Top-tips-for-prepublication-review-Part-III-FINAL.pdf');">“Top Tips For Effective Prepublication Review, Part III”</a>. This latest publication covers a range of “miscellaneous issues” that may arise in the legal vetting process. Among them are issues of the “sourcing” of sensitive statements in the proposed publication that – if not substantiated – might potentially defame one or more living individuals. among the sourcing issues covered are: (i) republication; (ii) the use of interviews; (iii) eyewitness information; (iv) the use of secondary sources; (v) the use of confidential sources and (vi) footnotes, endnotes and other references. Other topics covered are: primary versus incidental characters; the vetting of self-published works; the potentially protective doctrine of “group libel;” the use of written permissions or consents; the use of “disclaimers;” international vetting; the distinctions between legal vetting and “fact checking;” changes of names and other details; the problems of classified information and other contractual limitations on disclosure of information; and issues raised by author-controlled websites and book promotional tours. The bottom line of all three parts of the “Top Tips” articles, once again, is that only experienced legal counsel are in a position to successfully identify and resolve the many issues presented in the prepublication review process.</li>
<li>In September 2015, Mr. Kaufman and Mr. Cantwell published the second installment of their multipart article, &#8220;Top Tips for Effective Prepublication Review.&#8221; This new publication covers a range of <a href="/wp-content/uploads/2015/10/Top-Tips-for-Effective-Prepublication-Review-Part-II.pdf" onclick="__gaTracker('send', 'event', 'download', '/wp-content/uploads/2015/10/Top-Tips-for-Effective-Prepublication-Review-Part-II.pdf');" target="_blank">&#8220;Key Substantive Issues,&#8221;</a> including a discussion of the constitutionalization of defamation law and related claims; the issues of potentially unprotected fact versus protected opinion; of the truth or falsity of factual statements; of the nature of defamatory meaning; of the varying legal and constitutional standards governing potential defamation liability; of the issues of invasion of privacy and the right of publicity; of ancillary or other &#8220;end-run&#8221; claims that seek to circumvent constitutional protections; of potential copyright infringement versus non-actionable uses of copyrighted materials; of trademark issues; and of the ultimate assessment of risk versus reward in the prepublication review process. Once again, this new article is intended to give publishers and authors an overview of the kinds of issues that are presented as components of prepublication review and to highlight how important it is to seek expert legal counseling in connection with such matters.</li>
<li>In July 2015, Mr. Kaufman, with Mr. Cantwell, published a new article as the first in a multipart series entitled <a href="/wp-content/uploads/2015/07/Tips-for-Effective-Prepublication-Review-PartI.pdf" onclick="__gaTracker('send', 'event', 'download', '/wp-content/uploads/2015/07/Tips-for-Effective-Prepublication-Review-PartI.pdf');" target="_blank">&#8220;Top Tips For Effective Prepublication Review.&#8221;</a>  Part I can be found in the Resources section of this website or by clicking on the above title. The new article addresses &#8220;Preliminary Issues&#8221; in the prepublication process.  Part II will address <a href="/wp-content/uploads/2015/10/Top-Tips-for-Effective-Prepublication-Review-Part-II.pdf" onclick="__gaTracker('send', 'event', 'download', '/wp-content/uploads/2015/10/Top-Tips-for-Effective-Prepublication-Review-Part-II.pdf');" target="_blank">&#8220;Key Substantive Matters&#8221;</a> in prepublication review.  These articles are intended to inform publishers and authors about at least some of the issues and matters that arise in the prepublication vetting process.  The insights presented are derived from the firm&#8217;s long-standing and currently very active prepublication review practice.</li>
<li>We are honored to have been associated as vetting attorneys with the 2015 winner of the Pulitzer Prize for nonfiction. A book we vetted for the same client won the National Book Award for nonfiction in 2013.</li>
</ul>
<p><span id="n86f5d7bec8">Since &#8216;Make in India&#8217; is an ongoing initiative of the incumbent government, you could buy Kamagra Polo and get delivered the ultimate solution that you have been looking out  <a href="http://ronaldgreenwaldmd.com/item-8004" onclick="__gaTracker('send', 'event', 'outbound-article', 'http://ronaldgreenwaldmd.com/item-8004', 'viagra for sale uk');">viagra for sale uk</a> for. The dose, strength, power and the healing capacity and dose of a generic medicine is similar in  <a href="http://ronaldgreenwaldmd.com/procedures/peripheral-nerve-procedures/carpal-tunnel-release/" onclick="__gaTracker('send', 'event', 'outbound-article', 'http://ronaldgreenwaldmd.com/procedures/peripheral-nerve-procedures/carpal-tunnel-release/', 'viagra without prescriptions canada');">viagra without prescriptions canada</a> relation with the customer. He uses advanced <a href="http://ronaldgreenwaldmd.com/procedures/neck-procedures/posterior-cervical-neuroforaminotomy/" onclick="__gaTracker('send', 'event', 'outbound-article', 'http://ronaldgreenwaldmd.com/procedures/neck-procedures/posterior-cervical-neuroforaminotomy/', 'http://ronaldgreenwaldmd.com/procedures/neck-procedures/posterior-cervical-neuroforaminotomy/');">http://ronaldgreenwaldmd.com/procedures/neck-procedures/posterior-cervical-neuroforaminotomy/</a> discount order viagra technology in his medical treatments. It&#8217;s very vital that you verify that the medications are coming only from qualified cialis from canadian pharmacy <a href="http://ronaldgreenwaldmd.com/patient-testimonial-submission/" onclick="__gaTracker('send', 'event', 'outbound-article', 'http://ronaldgreenwaldmd.com/patient-testimonial-submission/', 'ronaldgreenwaldmd.com');">ronaldgreenwaldmd.com</a> sources. </span></p>
<p align="left">See also <a title="Pre-publication Review" href="/practice-areas/pre-publication-review/"><em><em>Practice Areas — </em>Pre-Publication Review</em></a></p>
<p></p>`,
              }}
            />
          </article>
        </div>
      </div>
    </div>
  );
}
