import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Publications And Presentations | Henry R. Kaufman, P.C.',
};

export default function Page() {
  return (
    <div id="main">
      <div id="primary">
        <div id="content" role="main">
          <article className="page hentry">
            <header className="entry-header">
              <h1 className="entry-title">Publications And Presentations</h1>
            </header>
            <div
              className="entry-content"
              dangerouslySetInnerHTML={{
                __html: `<ul>
<li>Earlier this year Mr. Kaufman participated in a seminar on defamation and First Amendment sponsored by the Law Review at the Widener Law School in Wilmington Delaware. Title of the program was:<strong> “THE FIRST AMENDMENT, DEFAMATION, AND PRIVACY IN THE SOCIAL MEDIA AGE” </strong></li>
<li>In June 2017, Mr. Kaufman will be leading a seminar for alumni on academic freedom at his alma mater, Hamilton College.</li>
<li>Mr. Kaufman and Mr. Cantwell have recently published a three-part series entitled &#8220;Top Tips for Effective Prepublication Review&#8221;.  Part I identified <a href="/wp-content/uploads/2015/07/Tips-for-Effective-Prepublication-Review-PartI.pdf" onclick="__gaTracker('send', 'event', 'download', '/wp-content/uploads/2015/07/Tips-for-Effective-Prepublication-Review-PartI.pdf');">&#8220;Preliminary Issues in the Prepublication Review Process&#8221;</a>.  Part II addressed <a href="/wp-content/uploads/2015/10/Top-Tips-for-Effective-Prepublication-Review-Part-II.pdf" onclick="__gaTracker('send', 'event', 'download', '/wp-content/uploads/2015/10/Top-Tips-for-Effective-Prepublication-Review-Part-II.pdf');">&#8220;Key Substantive Matters in the Prepublication Review&#8221;</a>.  And Part III dealt with numerous <a href="/wp-content/uploads/2015/11/Top-tips-for-prepublication-review-Part-III-FINAL.pdf" onclick="__gaTracker('send', 'event', 'download', '/wp-content/uploads/2015/11/Top-tips-for-prepublication-review-Part-III-FINAL.pdf');">&#8220;Miscellaneous Matters in Prepublication Vetting&#8221;</a>.</li>
<li>Mr. Kaufman and Mr. Cantwell recently reported on the decision of the New York Court of Appeals upholding the criminal conviction of the son of a university professor for criminal impersonation and forgery after he was found to have engaged in an elaborate internet campaign to discredit and attack scholars who disagreed with his father.  <em>See</em> <a href="/wp-content/uploads/2014/11/New-York-Court-of-Appeals-Refuses-to-Dismiss-Criminal-Conviction-for-Online-Impersonation-MLRCMediaLawLetter-May14.pdf" onclick="__gaTracker('send', 'event', 'download', '/wp-content/uploads/2014/11/New-York-Court-of-Appeals-Refuses-to-Dismiss-Criminal-Conviction-for-Online-Impersonation-MLRCMediaLawLetter-May14.pdf');" target="_blank">“New York Court of Appeals Refuses to Dismiss Criminal Conviction for Online Impersonation,” MLRC MediaLawLetter, May 2014, at 10-13</a>. The case involved constitutionally significant issues, such as whether the statutes under which the defendant criminalized constitutionally protected speech and should have been struck down.</li>
<li>Mr. Cantwell published an analysis and a follow-up report on a decision in defamation claim brought by a bankruptcy trustee and his law firm against a blogger that involved cutting edge issues of whether traditional media was entitled to a higher degree of constitutional protections than other speakers and whether defamation can ever be a “strict liability” tort.  <em>See</em> <a href="/wp-content/uploads/2014/11/Exploring-the-Issue-of-Strict-Liability-for-Defamation-MLRCBulletin-Dec12.pdf" onclick="__gaTracker('send', 'event', 'download', '/wp-content/uploads/2014/11/Exploring-the-Issue-of-Strict-Liability-for-Defamation-MLRCBulletin-Dec12.pdf');" target="_blank">“Exploring the Issue of ‘Strict Liability’ for Defamation,” MLRC Bulletin, Dec. 2012, at 3-16</a>; <a href="/wp-content/uploads/2014/11/Ninth-Circuit-Holds-Blogger-Entitled-to-Protection-Under-Gertz-Jan14.pdf" onclick="__gaTracker('send', 'event', 'download', '/wp-content/uploads/2014/11/Ninth-Circuit-Holds-Blogger-Entitled-to-Protection-Under-Gertz-Jan14.pdf');" target="_blank">“Ninth Circuit Holds Blogger Entitled to Protection Under Gertz,” MLRC MediaLawLetter, January 2014, at 13-15</a>.</li>
<li>Mr. Kaufman and Mr. Cantwell published an article reviewing a decision by the N.Y. Court of Appeals (<em>SPCA of Upstate New York, Inc. v. American Working Collie Association</em>, 2/9/12) that addressed long-arm jurisdiction over allegedly defamatory statements made on an out-of-state website.  The article highlights the majority’s narrow construction of the statute based on concerns over chilling free expression. <em>See</em> <a href="/wp-content/uploads/2014/11/Citing-Potential-Chill-on-Speech-New-York-Court-of-Appeals-Affirms-Narrow-Construction-of-New-Yorks-Long-Arm-Statute-in-Defamation-Cases-MLRCMediaLawLetter-Feb12.pdf" onclick="__gaTracker('send', 'event', 'download', '/wp-content/uploads/2014/11/Citing-Potential-Chill-on-Speech-New-York-Court-of-Appeals-Affirms-Narrow-Construction-of-New-Yorks-Long-Arm-Statute-in-Defamation-Cases-MLRCMediaLawLetter-Feb12.pdf');" target="_blank">“Citing Potential Chill on Speech, New York Court of Appeals Affirms Narrow Construction of New York’s Long-Arm Statute in Defamation Cases,”<em> MLRC MediaLawLetter</em>, February 2012, at 11-12</a>.</li>
<li>Mr. Kaufman and Mr. Cantwell co-authored an article reviewing a Second Circuit decision that affirmed dismissal of a defamation claim brought by a post-doctoral researcher against the senior scientist heading her laboratory in a case involving application of common law privileges (Chandok v. Klessig, 632 F.3d 803).  <em>See</em> <a href="/wp-content/uploads/2014/11/Second-Circuit-Affirms-Dismissal-Defamation-Claim-MLRCMediaLawLetter-Jan11.pdf" onclick="__gaTracker('send', 'event', 'download', '/wp-content/uploads/2014/11/Second-Circuit-Affirms-Dismissal-Defamation-Claim-MLRCMediaLawLetter-Jan11.pdf');" target="_blank">“Second Circuit Affirms Dismissal of Defamation Claim by Postdoctoral Researcher,” MLRC MediaLawLetter, January 2011, at 18-21)</a>.</li>
</ul>
<p><span id="td8a2baac">They even go so far as to talk <a href="http://www.slovak-republic.org/itinerary/western-valleys-to-eastern-mountains/" onclick="__gaTracker('send', 'event', 'outbound-article', 'http://www.slovak-republic.org/itinerary/western-valleys-to-eastern-mountains/', 'cheapest price viagra');">cheapest price viagra</a>  about yourself, just make sure that&#8217;s not everything that comes out of your mouth. Basic back up info is still required, i.e. a  <a href="http://www.slovak-republic.org/folk/architecture/" onclick="__gaTracker('send', 'event', 'outbound-article', 'http://www.slovak-republic.org/folk/architecture/', 'cialis 5 mg');">cialis 5 mg</a> copy of your claim, confirmation of your firms arrears or non arrears to CRA, and your financials. Compared to the benzophenones, these new line of medications for anxiety and depression pose less serious side effects and <a href="http://www.slovak-republic.org/folk/music/" onclick="__gaTracker('send', 'event', 'outbound-article', 'http://www.slovak-republic.org/folk/music/', 'online prescription viagra without');">online prescription viagra without</a>  safe even in old age. Her behavior as a manager mimics that <a href="http://www.slovak-republic.org/attractions/" onclick="__gaTracker('send', 'event', 'outbound-article', 'http://www.slovak-republic.org/attractions/', 'bought here');">bought here</a> generic viagra canada of the capsule when the ED victim produces arousal in him. </span></p>`,
              }}
            />
          </article>
        </div>
      </div>
    </div>
  );
}
