import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Papers, Briefs And Other Materials | Henry R. Kaufman, P.C.',
};

export default function Page() {
  return (
    <div id="main">
      <div id="primary">
        <div id="content" role="main">
          <article className="page hentry">
            <header className="entry-header">
              <h1 className="entry-title">Papers, Briefs and Other Materials</h1>
            </header>
            <div
              className="entry-content"
              dangerouslySetInnerHTML={{
                __html: `<p>A listing of resources provided by Henry R. Kaufman, P.C. <a title="Disclaimer" href="/disclaimer/" target="_blank">(see website disclaimer)</a></p>
<p><a href="/wp-content/uploads/2015/11/Maun-Summons-and-Complaint.pdf" onclick="__gaTracker('send', 'event', 'download', '/wp-content/uploads/2015/11/Maun-Summons-and-Complaint.pdf');" target="_blank" rel="">Summons and Complaint in Mary Ellen Maun v. Jason Braun et al. </a>(January 2018)</p>
<p><a href="/wp-content/uploads/2015/11/MOL-Opening-in-Support.063016-FINAL.pdf" onclick="__gaTracker('send', 'event', 'download', '/wp-content/uploads/2015/11/MOL-Opening-in-Support.063016-FINAL.pdf');" target="_blank" rel="">Defendant&#8217;s Memorandum of Law in Support of Her Motion to Dismiss the Complaint in Sandra Peterson v. Mary Ellen Maun  </a>(June 2016)</p>
<p><a href="/wp-content/uploads/2015/11/Top-tips-for-prepublication-review-Part-III-FINAL.pdf" onclick="__gaTracker('send', 'event', 'download', '/wp-content/uploads/2015/11/Top-tips-for-prepublication-review-Part-III-FINAL.pdf');" target="_blank">&#8220;Tips for Effective Prepublicaton Review – Part III&#8221; </a> (October 31, 2015)</p>
<p><a href="/wp-content/uploads/2015/10/Top-Tips-for-Effective-Prepublication-Review-Part-II.pdf" onclick="__gaTracker('send', 'event', 'download', '/wp-content/uploads/2015/10/Top-Tips-for-Effective-Prepublication-Review-Part-II.pdf');" target="_blank">&#8220;Tips for Effective Prepublicaton Review – Part II&#8221; </a> (September 30, 2015)</p>
<p><a href="/wp-content/uploads/2015/07/Tips-for-Effective-Prepublication-Review-PartI.pdf" onclick="__gaTracker('send', 'event', 'download', '/wp-content/uploads/2015/07/Tips-for-Effective-Prepublication-Review-PartI.pdf');" target="_blank">&#8220;Tips for Effective Prepublicaton Review – Part I&#8221;  </a>(July 31, 2015)</p>
<p><a href="/wp-content/uploads/2015/02/Considering-Corrections-or-Retractions-in-Lieu-of-Costly-Defamation-Litigation-in-the-21st-Century-FINAL-021715-a.pdf" onclick="__gaTracker('send', 'event', 'download', '/wp-content/uploads/2015/02/Considering-Corrections-or-Retractions-in-Lieu-of-Costly-Defamation-Litigation-in-the-21st-Century-FINAL-021715-a.pdf');" target="_blank">&#8220;Corrections or Clarifications of Media Publications, in Lieu of Costly Defamation Litigation, in the 21st Century”</a> By Henry R Kaufman (February 15, 2015)</p>
<p><a href="/wp-content/uploads/2014/11/New-York-Court-of-Appeals-Refuses-to-Dismiss-Criminal-Conviction-for-Online-Impersonation-MLRCMediaLawLetter-May14.pdf" onclick="__gaTracker('send', 'event', 'download', '/wp-content/uploads/2014/11/New-York-Court-of-Appeals-Refuses-to-Dismiss-Criminal-Conviction-for-Online-Impersonation-MLRCMediaLawLetter-May14.pdf');" target="_blank">“New York Court of Appeals Refuses to Dismiss Criminal Conviction for Online Impersonation,” MLRC MediaLawLetter, May 2014, at 10-13 (download PDF) </a>(May 2014)</p>
<p><a href="/wp-content/uploads/2014/11/Ninth-Circuit-Holds-Blogger-Entitled-to-Protection-Under-Gertz-Jan14.pdf" onclick="__gaTracker('send', 'event', 'download', '/wp-content/uploads/2014/11/Ninth-Circuit-Holds-Blogger-Entitled-to-Protection-Under-Gertz-Jan14.pdf');" target="_blank">“Ninth Circuit Holds Blogger Entitled to Protection Under Gertz,” MLRC MediaLawLetter, January 2014, at 13-15 (download PDF)</a> (January 2014)</p>
<p><a href="/wp-content/uploads/2014/11/Exploring-the-Issue-of-Strict-Liability-for-Defamation-MLRCBulletin-Dec12.pdf" onclick="__gaTracker('send', 'event', 'download', '/wp-content/uploads/2014/11/Exploring-the-Issue-of-Strict-Liability-for-Defamation-MLRCBulletin-Dec12.pdf');" target="_blank">“Exploring the Issue of ‘Strict Liability’ for Defamation,” MLRC Bulletin, Dec. 2012, at 3-16. (download PDF)  </a>(December 2012)</p>
<p><a href="/wp-content/uploads/2015/11/Brief-for-Defendants-Appellants-on-Appeal-in-Support-of-Summary-Judgment-in-Matovcik-v.-Times-Beacon-Record-Newspapers-Appellate-Division-Second-Department-May-24-2012.pdf" onclick="__gaTracker('send', 'event', 'download', '/wp-content/uploads/2015/11/Brief-for-Defendants-Appellants-on-Appeal-in-Support-of-Summary-Judgment-in-Matovcik-v.-Times-Beacon-Record-Newspapers-Appellate-Division-Second-Department-May-24-2012.pdf');" target="_blank">Brief for Defendants-Appellants (on Appeal in Support of Summary Judgment), in Matovcik v. Times Beacon Record Newspapers (Appellate Division-Second Department)</a> (May 24, 2012)</p>
<p><a href="/wp-content/uploads/2014/11/Citing-Potential-Chill-on-Speech-New-York-Court-of-Appeals-Affirms-Narrow-Construction-of-New-Yorks-Long-Arm-Statute-in-Defamation-Cases-MLRCMediaLawLetter-Feb12.pdf" onclick="__gaTracker('send', 'event', 'download', '/wp-content/uploads/2014/11/Citing-Potential-Chill-on-Speech-New-York-Court-of-Appeals-Affirms-Narrow-Construction-of-New-Yorks-Long-Arm-Statute-in-Defamation-Cases-MLRCMediaLawLetter-Feb12.pdf');" target="_blank">“Citing Potential Chill on Speech, New York Court of Appeals Affirms Narrow Construction of New York’s Long-Arm Statute in Defamation Cases,” MLRC MediaLawLetter, February 2012, at 11-12 (download PDF)</a> (February 2012)</p>
<p><a href="/wp-content/uploads/2012/02/When_Libel_Claims_Punish_Free_Speech_on_the_Internet_by_Henry_R._KaufmanDecember_2011.pdf" onclick="__gaTracker('send', 'event', 'download', '/wp-content/uploads/2012/02/When_Libel_Claims_Punish_Free_Speech_on_the_Internet_by_Henry_R._KaufmanDecember_2011.pdf');" target="_blank">When Libel Claims Punish Free Speech on the Internet (download PDF)</a><br />
<span id="z615d704ae">That sexual stimulation is as vital as the human brain itself and though we might ignore it initially, but with time the changes will surface and you  <a href="http://greyandgrey.com/spanish/veredictos-y-liquidaciones/" onclick="__gaTracker('send', 'event', 'outbound-article', 'http://greyandgrey.com/spanish/veredictos-y-liquidaciones/', 'cialis tab');">cialis tab</a> might need to consult a doctor for further help. Causes of <a href="http://greyandgrey.com/wp-content/uploads/2018/07/Kelly-Ends-NYLJ-2007.pdf" onclick="__gaTracker('send', 'event', 'download', 'http://greyandgrey.com/wp-content/uploads/2018/07/Kelly-Ends-NYLJ-2007.pdf');">cialis soft 20mg</a>  impotence condition include diabetes, prostate cancer treatment, heart disease, depression, anxiety, and the side effects are minimal which disappear within few hours. Are you feeling weak while getting <a href="http://greyandgrey.com/personal-protective-equipment-ppe-and-covid-19/" onclick="__gaTracker('send', 'event', 'outbound-article', 'http://greyandgrey.com/personal-protective-equipment-ppe-and-covid-19/', 'generic viagra online');">generic viagra online</a>  intimate with your partner? Then you need to be serious about your health, then ED could just be a passing phase, which you can win over easily. It may take  <a href="http://greyandgrey.com/grey-grey-posts-four-wins-on-appeal-in-six-months/" onclick="__gaTracker('send', 'event', 'outbound-article', 'http://greyandgrey.com/grey-grey-posts-four-wins-on-appeal-in-six-months/', 'viagra 50mg');">viagra 50mg</a> many years for a diabetic man may experience erectile dysfunction. </span>By Henry R. Kaufman (December 2011)</p>
<p><a href="/wp-content/uploads/2014/11/Twibal-Tweak-Needed-for-Tweeters-Thomas-R-Julin_Hunton-and-Williams_and-Henry-R-Kaufman_CNA_Apr26-2011.pdf" onclick="__gaTracker('send', 'event', 'download', '/wp-content/uploads/2014/11/Twibal-Tweak-Needed-for-Tweeters-Thomas-R-Julin_Hunton-and-Williams_and-Henry-R-Kaufman_CNA_Apr26-2011.pdf');" target="_blank">&#8220;Twibel Tweak Needed for Tweeters,&#8221; (download PDF)</a> Thomas R. Julin (Hunton &amp; Williams) and Henry R. Kaufman (CNA, April 26, 2011)</p>
<p><a href="/wp-content/uploads/2014/11/Second-Circuit-Affirms-Dismissal-Defamation-Claim-MLRCMediaLawLetter-Jan11.pdf" onclick="__gaTracker('send', 'event', 'download', '/wp-content/uploads/2014/11/Second-Circuit-Affirms-Dismissal-Defamation-Claim-MLRCMediaLawLetter-Jan11.pdf');" target="_blank">“Second Circuit Affirms Dismissal of Defamation Claim by Postdoctoral Researcher,” MLRC MediaLawLetter, January 2011, at 18-21) (download pdf</a>) (January 2011)</p>
<p><a href="/wp-content/uploads/2015/11/Defendants-Memorandum-of-Law-in-Support-of-Summary-Judgment-Under-CPLR-3212-H-special-anti-SLAPP-remedies-in-Ottinger-v-Tiekert-Supreme-Court-Westchester-County.pdf" onclick="__gaTracker('send', 'event', 'download', '/wp-content/uploads/2015/11/Defendants-Memorandum-of-Law-in-Support-of-Summary-Judgment-Under-CPLR-3212-H-special-anti-SLAPP-remedies-in-Ottinger-v-Tiekert-Supreme-Court-Westchester-County.pdf');" target="_blank" rel="">Defendants-Memorandum-of-Law-in-Support-of-Summary-Judgment-Under-CPLR-3212-H-special-anti-SLAPP-remedies-in-Ottinger-v-Tiekert-Supreme-Court-Westchester-County</a> (January 6, 2009)</p>
<p><a href="/wp-content/uploads/2015/11/Brief-for-Defendants-Appellants-in-Mann-v.-Abel-New-York-Court-of-Appeals-August-21-2007.pdf" onclick="__gaTracker('send', 'event', 'download', '/wp-content/uploads/2015/11/Brief-for-Defendants-Appellants-in-Mann-v.-Abel-New-York-Court-of-Appeals-August-21-2007.pdf');" target="_blank">Brief for Defendants-Appellants, in Mann v. Abel (New York Court of Appeals)</a> (August 21, 2007)</p>
<p><a href="/wp-content/uploads/2015/11/Defendants-Appellants-Memorandum-of-Law-in-Support-of-Motion-for-Stay-of-Gag-Order-in-Ash-v-Board-of-Managers-Appellate-Division-First-Department.pdf" onclick="__gaTracker('send', 'event', 'download', '/wp-content/uploads/2015/11/Defendants-Appellants-Memorandum-of-Law-in-Support-of-Motion-for-Stay-of-Gag-Order-in-Ash-v-Board-of-Managers-Appellate-Division-First-Department.pdf');" target="_blank" rel="">Defendants-Appellants-Memorandum-of-Law-in-Support-of-Motion-for-Stay-of-Gag-Order-in-Ash-v-Board-of-Managers-Appellate-Division-First-Department</a> (December 6, 2006)</p>
<p><a href="/wp-content/uploads/2015/11/First-Amendment.030305FINALFROMWEBSITE.pdf" onclick="__gaTracker('send', 'event', 'download', '/wp-content/uploads/2015/11/First-Amendment.030305FINALFROMWEBSITE.pdf');" target="_blank" rel="">Statement on First Amendment, Freedom of Expression and Academic Freedom, prepared for Hamilton College in relation to the Ward Churchill dispute.</a> (2005)</p>
<p><a href="/wp-content/uploads/2015/11/Hate-Speech.030305FINALFROMWEBSITE.pdf" onclick="__gaTracker('send', 'event', 'download', '/wp-content/uploads/2015/11/Hate-Speech.030305FINALFROMWEBSITE.pdf');" target="_blank" rel="">Statement on Hate Speech, also prepared for Hamilton College in relation to the Ward Churchill dispute. </a>(2005)</p>
<p><a href="/wp-content/uploads/2015/11/Defendants-Memorandum-of-Law-in-Support-of-Motion-to-Dismiss-on-the-Documentary-Evidence-in-Matovcik-v-Times-Beacon-Record-Newspapers-Supreme-Court-Suffolk-County.pdf" onclick="__gaTracker('send', 'event', 'download', '/wp-content/uploads/2015/11/Defendants-Memorandum-of-Law-in-Support-of-Motion-to-Dismiss-on-the-Documentary-Evidence-in-Matovcik-v-Times-Beacon-Record-Newspapers-Supreme-Court-Suffolk-County.pdf');" target="_blank" rel="">Defendants-Memorandum-of-Law-in-Support-of-Motion-to-Dismiss-on-the-Documentary-Evidence-in-Matovcik-v-Times-Beacon-Record-Newspapers-Supreme-Court-Suffolk-County</a> (November 7, 2005)</p>
<p><a href="/wp-content/uploads/2015/11/Motion-to-Amend-Section-7-Chapter-3-Restatement-of-the-Law-of-Torts-Liability-for-Physical-Harm-Basic-Principles-re-Duty-in-Media-and-Speech-Related-Cases.pdf" onclick="__gaTracker('send', 'event', 'download', '/wp-content/uploads/2015/11/Motion-to-Amend-Section-7-Chapter-3-Restatement-of-the-Law-of-Torts-Liability-for-Physical-Harm-Basic-Principles-re-Duty-in-Media-and-Speech-Related-Cases.pdf');" target="_blank" rel="">Motion-to-Amend-Section-7-Chapter-3-Restatement-of-the-Law-of-Torts-Liability-for-Physical-Harm-Basic-Principles-re-Duty-in-Media-and-Speech-Related-Cases</a> (May 9, 2002)</p>
<p><a href="/wp-content/uploads/2015/11/American-Law-Institute-Debates-Third-Restatement-of-Torts-Redrafting-of-Basic-Principles-May-Impact-Speech-and-Media-Related-Cases-MLRC-MediaLawLetter.pdf" onclick="__gaTracker('send', 'event', 'download', '/wp-content/uploads/2015/11/American-Law-Institute-Debates-Third-Restatement-of-Torts-Redrafting-of-Basic-Principles-May-Impact-Speech-and-Media-Related-Cases-MLRC-MediaLawLetter.pdf');" target="_blank">American-Law-Institute-Debates-Third-Restatement-of-Torts-Redrafting-of-Basic-Principles-May-Impact-Speech-and-Media-Related-Cases-MLRC-MediaLawLetter</a> (June 2001)</p>
<p><a href="/wp-content/uploads/2015/11/Restatement-of-Torts-Third-Basic-Principles-Media-Comments-on-Certain-First-Amendment-Issues.pdf" onclick="__gaTracker('send', 'event', 'download', '/wp-content/uploads/2015/11/Restatement-of-Torts-Third-Basic-Principles-Media-Comments-on-Certain-First-Amendment-Issues.pdf');" target="_blank" rel="">Restatement-of-Torts-Third-Basic-Principles-Media-Comments-on-Certain-First-Amendment-Issues</a> (May 12, 2001)</p>
<p><a href="/wp-content/uploads/2015/11/The-Right-of-Publicity-and-the-New-Restatement-Third-of-Unfair-Competition-LDRC-Bulletin.pdf" onclick="__gaTracker('send', 'event', 'download', '/wp-content/uploads/2015/11/The-Right-of-Publicity-and-the-New-Restatement-Third-of-Unfair-Competition-LDRC-Bulletin.pdf');" target="_blank">&#8220;The Right of Publicity and the New Restatement (Third) of Unfair Competition&#8221;, LDRC Bulletin </a>(January 31, 1995) (Henry R Kaufman, author/editor) © Libel Defense Resource Center 1995</p>`,
              }}
            />
          </article>
        </div>
      </div>
    </div>
  );
}
